### ISSUE TITLE
Add share button to "exercise completed" and "guide completed" views

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-atheneum#240]
So I can show the world how cool I am! :yum:

This should add a Tweet and Post on Facebook button. Ability to track those links should be nice, so we now if the people uses it.

**Comment by flbulgarelli** [comment]
What about the following?

@aguspina @faloi 

![screenshot - 070916 - 17 50 04](https://cloud.githubusercontent.com/assets/677436/18328105/c8a75b90-7523-11e6-922f-6e30843e6c66.png)

**Comment by aguspina** [comment]
I think it's not clear whether i'm sharing my achievement or guide's corollary. Maybe if you try in the popup header?

**Comment by faloi** [comment]
I don't like it... what about positioning it above the _"Para pensar"_, aligned to the right?

**Comment by flbulgarelli** [comment]
Here there are some alternatives - I personally don't love any of them. 

![option1](https://cloud.githubusercontent.com/assets/677436/18418820/ac2aabcc-7823-11e6-830f-3d4bed2b6213.png)

![option2](https://cloud.githubusercontent.com/assets/677436/18418821/b13a5d06-7823-11e6-8509-5ad1e1972dfd.png)

![option3](https://cloud.githubusercontent.com/assets/677436/18418822/b599c530-7823-11e6-8136-8a5267fc8639.png)

**Comment by flbulgarelli** [comment]
Actually I have just noticed that the corollary popup's title has too much margin after the title, and that the title is centered instead of left justified. 

If we put the share box after it, left-justified, the result is better IMHO: 

![option5](https://cloud.githubusercontent.com/assets/677436/18418893/58620362-7825-11e6-8f77-5dafb127d63a.png)

**Comment by flbulgarelli** [comment]
PS: I'd also add exclamation marks to the title, and fix it's left margin.

**Comment by flbulgarelli** [comment]
Final offtopic comment - it may be another issue -: always using the same expression _¡Felicitaciones!_ may reduce its impact on the student, since it sound too _robotic_. Perhaps we could have a few congratulation phrases and shuffle and use any of them randomly, like _Felicitaciones_, _Excelente_, _Bien hecho_, _Bravo_, _Hurra_, and so on. A more _argento_ approach may include expressions like _Esa_, _Bien ahí_, _Choque esos cinco :hand:_, _Groso/a_, _Grande_.

**Comment by faloi** [comment]
What about this one?

![b599c530-7823-11e6-8136-8a5267fc8639](https://cloud.githubusercontent.com/assets/1585835/18458805/bbe1e360-793a-11e6-92e5-0605690df77b.png)

**Comment by aguspina** [comment]
It's the best option so far
