### ISSUE TITLE
Add exercise dependencies

### ISSUE THREAD

**Issue by fedescarpa** [mumuki/mumuki-atheneum#455]
Exercises should depend on other exercise from the guide. It would be nice the current code depends from other written by the student. It could be attached to default code.

**Comment by fedescarpa** [comment]
Like @matifreyre says:
> Many guides are incremental and a given solution (function, method, etc.) is needed in later exercises.
> 
> Sometimes it's possible that students don't remember their own solutions. This can be as simple as forgetting the order of the parameters or how they named an auxiliary function. Forcing the student to go to the previous exercise to check it and then back to the current can turn annoying.
> 
> The same way we can decide to show "Extra code" or not, it could be helpful for them to be able to see their own submitted code of previous exercises.

**Comment by flbulgarelli** [comment]
Finally we have decided to implement this as another interpolation directive: now default code can have a `/*...previousContent...*/` inclusion directive that interpolates previous solution. 

It may be added to the extra content in the future if someone needs it, in order to use previous content as  extra content.

**Comment by flbulgarelli** [comment]
@mmatos @mmfreyre that allows editors to write exercises that depend on previous exercises solutions without having to copy-paste them
