### ISSUE TITLE
Sandbox

### ISSUE THREAD

**Issue by Charlyzzz** [mumuki/mumuki-atheneum#460]
How about a sandbox mode? Having a place to play around, without even opening an excercise might be useful

**Comment by flbulgarelli** [comment]
Event with our current technology, it is actually possible to do that. 

But why? What features should it have? Why would you prefer it over the original offline development environment? Where would you find it in the UI? When would you use it? Or event more, why should it be inside the atheneum ? How would you save your work? Should you be able to handle multiple workspaces, or limit the user to just one at a time? 

Please remember that atheneum - the main and original component of mumuki - is just an online platform for solving exercises. It is neither a whole educative environment, nor an IDE. 

It may be, however, part of an integrated educative environment, like the scratch environment. 

That means that although we really like your idea, we are not going to implement in any near future, since it is quite complex, and is not in our current roadmap.

However, you can implement it by yourself. And we **really** encourage you to do so. 

Runners expose  a nice public API, so the execution-in-the-cloud is already there. The editor is a plain ACE editor that already has everything you need - or at least, everything we offer currently -, we also offer some gems to interacting with a runner and other of our services - so such tool could be independently developed on top of some of the mumuki components. 

Since our documentation is nowadays pretty scarce, you will need our help, but we would be pleased to offer it.
