### ISSUE TITLE
Improve `start now` button navigation

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-atheneum#628]

**Comment by aguspina** [comment]
Remove start now from chapter page

**Comment by aguspina** [comment]
Start now on landing page, should redirect to last exercise

**Comment by flbulgarelli** [comment]
@aguspina we did a big mistake here. 

We are redirecting to the last exercise or first exercise. But we should redirect to the last or first **guide**.

The guide page has important information that the student must read in order to understand what she is  doing. Can we fix or rollback this change?
